# Generated by Django 4.2.2 on 2023-06-29 20:11

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCateorgy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='catlog/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCateorgy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='catlog/subcatlog')),
                ('main_cateorgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catlog.maincateorgy')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('price', models.IntegerField(default=0)),
                ('available_count', models.IntegerField(default=0)),
                ('is_small_size', models.BooleanField(default=False)),
                ('is_medium_size', models.BooleanField(default=False)),
                ('is_large_size', models.BooleanField(default=False)),
                ('is_extra_large_size', models.BooleanField(default=False)),
                ('sub_cateorgy', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='catlog.subcateorgy')),
            ],
        ),
        migrations.CreateModel(
            name='ProdReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300, null=True)),
                ('stars', models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisified'), (3, 'Good'), (4, 'Awesome'), (5, 'Phenominal')])),
                ('review_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catlog.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catlog/subcatlog/product')),
                ('image_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catlog.product')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catlog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
