# Generated by Django 4.2.2 on 2023-06-23 08:56

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCateorgy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='catlog/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCateorgy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='catlog/subcatlog')),
                ('MainCateorgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catlog.maincateorgy')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('size', models.CharField(choices=[('S', 'small'), ('M', 'Mdeium'), ('L', 'Large'), ('XL', 'Extra large')], max_length=300)),
                ('SubCateorgy', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='catlog.subcateorgy')),
            ],
        ),
        migrations.CreateModel(
            name='ProdReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300, null=True)),
                ('stars', models.IntegerField(choices=[(1, 'Poor'), (2, 'Satisified'), (3, 'Good'), (4, 'Awesome'), (5, 'Phenominal')])),
                ('review_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catlog.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProdImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catlog/subcatlog/product')),
                ('image_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catlog.products')),
            ],
        ),
    ]
