# Generated by Django 4.2.2 on 2023-07-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_extra_large_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_large_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_medium_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_small_size',
        ),
        migrations.CreateModel(
            name='SizeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catlog.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catlog.sizechart')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catlog.sizechart')),
                ('sub_cateorgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catlog.subcateorgy')),
            ],
        ),
    ]
