# Generated by Django 4.2.2 on 2023-07-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0003_alter_sizeproduct_product_alter_sizeproduct_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeproduct',
            name='size',
        ),
        migrations.AddField(
            model_name='sizeproduct',
            name='size',
            field=models.ManyToManyField(to='catlog.sizechart'),
        ),
    ]
