# Generated by Django 4.2.2 on 2023-06-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0004_alter_prodreview_reviewed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='SubCateorgy',
            new_name='sub_cateorgy',
        ),
        migrations.RenameField(
            model_name='subcateorgy',
            old_name='MainCateorgy',
            new_name='main_cateorgy',
        ),
    ]
