# Generated by Django 4.2.2 on 2023-07-24 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0004_remove_sizeproduct_size_sizeproduct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catlog.product'),
        ),
    ]
