# Generated by Django 4.2.2 on 2023-07-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0005_alter_sizeproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeproduct',
            name='size',
        ),
        migrations.AddField(
            model_name='sizeproduct',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catlog.sizechart'),
            preserve_default=False,
        ),
    ]
