# Generated by Django 4.2.2 on 2023-07-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_product_cart_size'),
        ('catlog', '0007_alter_sizeproduct_available_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeProduct',
            new_name='ProductBySize',
        ),
    ]
