# Generated by Django 4.2.2 on 2023-07-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_merge_0004_orders_size_0006_delete_cartorder'),
        ('payment', '0002_transaction_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order_id_2',
        ),
        migrations.DeleteModel(
            name='Transaction_Cart',
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_id_2',
            field=models.ManyToManyField(to='order.orders'),
        ),
    ]
