# Generated by Django 4.2.2 on 2023-06-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(help_text='Enter your Email', max_length=255, unique=True, verbose_name='Users Email'),
        ),
    ]
