# Generated by Django 4.2.2 on 2023-07-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address_state_alter_address_country'),
        ('accounts', '0005_alter_user_username'),
    ]

    operations = [
    ]
