# Generated by Django 4.2.2 on 2023-07-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20230701_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='prefer not to say', max_length=100),
        ),
    ]
