# Generated by Django 4.2.2 on 2023-06-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_cart',
            name='price',
        ),
    ]
