# Generated by Django 4.2.2 on 2023-07-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0001_initial'),
        ('cart', '0002_remove_product_cart_product_product_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_cart',
            name='product',
        ),
        migrations.AddField(
            model_name='product_cart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catlog.product'),
            preserve_default=False,
        ),
    ]
