# Generated by Django 4.2.2 on 2023-07-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_cart',
            field=models.ManyToManyField(to='cart.product_cart'),
        ),
    ]
