# Generated by Django 4.2.2 on 2023-07-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
