# Generated by Django 4.2.2 on 2023-07-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_product_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_cart',
            name='size',
        ),
    ]
