# Generated by Django 4.2.2 on 2023-07-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_product_cart_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_cart',
            old_name='product',
            new_name='product_by_size',
        ),
    ]
