# Generated by Django 4.2.2 on 2023-07-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_status_orders_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_type',
            field=models.CharField(choices=[('1', 'Online Payment'), ('2', 'Cash on delivery')], default='2', max_length=200),
        ),
    ]
