# Generated by Django 4.2.2 on 2023-07-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orders_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='size',
            field=models.CharField(default='S', max_length=200),
        ),
    ]
