# Generated by Django 4.2.2 on 2023-07-11 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
        ('order', '0003_orders_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('1', 'Dispatched'), ('2', 'shipped'), ('3', 'on the way')], max_length=200)),
                ('payment_type', models.CharField(choices=[('1', 'Online Payment'), ('2', 'Cash on delivery')], default='2', max_length=200)),
                ('payment_status', models.CharField(choices=[('1', 'paid'), ('2', 'Not paid')], default='2', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.product_cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
