# Generated by Django 4.2.2 on 2023-07-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_cartorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='cart',
        ),
    ]
