# Generated by Django 4.2.2 on 2023-07-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_cartorder_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartOrder',
        ),
    ]
