# Generated by Django 4.2.2 on 2023-07-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orders_size'),
        ('order', '0006_delete_cartorder'),
    ]

    operations = [
    ]
