# Generated by Django 4.2.2 on 2023-07-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_merge_0004_orders_size_0006_delete_cartorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='size',
        ),
    ]
