# Generated by Django 4.2.2 on 2023-07-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orders_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='product',
            new_name='product_by_size',
        ),
    ]
